# Generated by Django 6.0.7 on 2026-07-12 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('reserved', 'Reserved'), ('checked-in', 'Checked in'), ('completed', 'Completed')], default='reserved', max_length=20),
        ),
    ]
