[mypy]
plugins = mypy_django_plugin.main
python_version = 3.14
check_untyped_defs = True

[mypy.plugins.django-stubs]
django_settings_module = hotel_system.settings

[mypy-xhtml2pdf.*]
ignore_missing_imports = True

[mypy-matplotlib.*]
ignore_missing_imports = True
